[package]
name = "abuildtester"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
ctrlc = "3.2.0"
nix = "0.22.1"
